exclude: (^|/)\.[^/]+/|^(3rdparty/|build/|dist/|cmake-build-[^/]+/)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        files: ^\.pre-commit-config\.yaml$
      - id: check-toml
        files: ^pyproject\.toml$
      - id: end-of-file-fixer
        files: ^(CMakeLists\.txt|pyproject\.toml|\.pre-commit-config\.yaml|(scinthil|profile/python|tests/python)/.*\.py|(csrc|profile|tests)/(.*/)?CMakeLists\.txt|(csrc|scinthil)/cmake/.*\.cmake|(csrc|profile|tests)/.*\.(cu|cuh|h|hpp|cc|cpp))$
      - id: trailing-whitespace
        files: ^(CMakeLists\.txt|pyproject\.toml|\.pre-commit-config\.yaml|(scinthil|profile/python|tests/python)/.*\.py|(csrc|profile|tests)/(.*/)?CMakeLists\.txt|(csrc|scinthil)/cmake/.*\.cmake|(csrc|profile|tests)/.*\.(cu|cuh|h|hpp|cc|cpp))$

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v22.1.0
    hooks:
      - id: clang-format
        files: ^(csrc|profile|tests)/.*\.(cu|cuh|h|hpp|cc|cpp)$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix]
        files: ^(scinthil|profile/python|tests/python)/.*\.py$
      - id: ruff-format
        files: ^(scinthil|profile/python|tests/python)/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        files: ^scinthil/.*\.py$
        pass_filenames: false
